apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
  labels:
    app: catalog-service
data:
  SPRING_DATASOURCE_PASSWORD: cTVzT2w0R0pmNw==
# to be moved later in GitHub Secrets Manager


