server:
  port: 8080
spring:
  application:
    name: catalog-service
# profiles set with kustomize overlays, and for local development in IDE configuration
# profiles:
    #active: local, kafka-enabled
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    topic: my-topic
management:
  health:
    elasticsearch:
      enabled: false
  endpoint:
    health:
      elasticsearch:
        enabled: true
  endpoints:
    web:
      exposure:
        #include: "*" # Expose all Actuator endpoints (if using Actuator)
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false # Disable Actuator security
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    root: INFO
    com.store: DEBUG
    org.springframework.data.elasticsearch.client: DEBUG
    org.elasticsearch.client: DEBUG
#    apache.kafka: DEBUG
security:
  ignored: ${SECURITY_IGNORED}
  basic:
    enabled: ${SECURITY_BASIC_ENABLED}
  user:
    name: ${SECURITY_USER_NAME}
    password: ${SECURITY_USER_PASSWORD}
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY}
