server:
  port: 8080
spring:
  application:
    name: catalog-service
  profiles:
#    active: dev  # Default to dev if no profile is explicitly set
    active: dev, kafka-enabled  # Default to dev if no profile is explicitly set
  kafka:
    consumer:
      group-id: catalog-service-group
    topic: my-topic
management:
  endpoint:
    health:
      elasticsearch:
        enabled: true
  endpoints:
    web:
      exposure:
        #include: "*" # Expose all Actuator endpoints (if using Actuator)
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: false # Disable Actuator security
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
logging:
  level:
    root: INFO
    com.store: DEBUG
#    org:
#      springframework:
#        data:
#          elasticsearch:
#            client: DEBUG
#      apache:
#        kafka: DEBUG
security:
  jwt:
    secret-key: ZDbiJXqjL06maIhSmDftCQy7bD5J3fLFOFlOlgmNa+U=