server:
  port: 8080
spring:
  application:
    name: catalog-service
  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres
    username: postgres
    password: VnUWe2XNUg
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # options: validate, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
      enabled: false
  kafka:
    bootstrap-servers: kafka-cluster-kafka-bootstrap.kafka:9092
security:
  ignored: /**
  basic:
    enabled: false # Disables basic authentication
  user:
    name: user # Default username (optional if disabling security)
    password: password # Default password (optional if disabling security)

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all Actuator endpoints (if using Actuator)
  security:
    enabled: false # Disable Actuator security

