apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  template:
    spec:
      containers:
        - name: catalog-service
          envFrom:
            - configMapRef:
                name: catalog-service-config
            - secretRef:
                name: catalog-service-secret
